/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/raihankhan/httpApiServer-controller/pkg/apis/raihankhan.github.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeApiservers implements ApiserverInterface
type FakeApiservers struct {
	Fake *FakeSamplecontrollerV1alpha1
	ns   string
}

var apiserversResource = schema.GroupVersionResource{Group: "samplecontroller.k8s.io", Version: "v1alpha1", Resource: "apiservers"}

var apiserversKind = schema.GroupVersionKind{Group: "samplecontroller.k8s.io", Version: "v1alpha1", Kind: "Apiserver"}

// Get takes name of the apiserver, and returns the corresponding apiserver object, and an error if there is any.
func (c *FakeApiservers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Apiserver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(apiserversResource, c.ns, name), &v1alpha1.Apiserver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Apiserver), err
}

// List takes label and field selectors, and returns the list of Apiservers that match those selectors.
func (c *FakeApiservers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ApiserverList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(apiserversResource, apiserversKind, c.ns, opts), &v1alpha1.ApiserverList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ApiserverList{ListMeta: obj.(*v1alpha1.ApiserverList).ListMeta}
	for _, item := range obj.(*v1alpha1.ApiserverList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested apiservers.
func (c *FakeApiservers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(apiserversResource, c.ns, opts))

}

// Create takes the representation of a apiserver and creates it.  Returns the server's representation of the apiserver, and an error, if there is any.
func (c *FakeApiservers) Create(ctx context.Context, apiserver *v1alpha1.Apiserver, opts v1.CreateOptions) (result *v1alpha1.Apiserver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(apiserversResource, c.ns, apiserver), &v1alpha1.Apiserver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Apiserver), err
}

// Update takes the representation of a apiserver and updates it. Returns the server's representation of the apiserver, and an error, if there is any.
func (c *FakeApiservers) Update(ctx context.Context, apiserver *v1alpha1.Apiserver, opts v1.UpdateOptions) (result *v1alpha1.Apiserver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(apiserversResource, c.ns, apiserver), &v1alpha1.Apiserver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Apiserver), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeApiservers) UpdateStatus(ctx context.Context, apiserver *v1alpha1.Apiserver, opts v1.UpdateOptions) (*v1alpha1.Apiserver, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(apiserversResource, "status", c.ns, apiserver), &v1alpha1.Apiserver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Apiserver), err
}

// Delete takes name of the apiserver and deletes it. Returns an error if one occurs.
func (c *FakeApiservers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(apiserversResource, c.ns, name), &v1alpha1.Apiserver{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeApiservers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(apiserversResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ApiserverList{})
	return err
}

// Patch applies the patch and returns the patched apiserver.
func (c *FakeApiservers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Apiserver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(apiserversResource, c.ns, name, pt, data, subresources...), &v1alpha1.Apiserver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Apiserver), err
}
