/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/raihankhan/httpApiServer-controller/pkg/apis/raihankhan.github.io/v1alpha1"
	scheme "github.com/raihankhan/httpApiServer-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ApiserversGetter has a method to return a ApiserverInterface.
// A group's client should implement this interface.
type ApiserversGetter interface {
	Apiservers(namespace string) ApiserverInterface
}

// ApiserverInterface has methods to work with Apiserver resources.
type ApiserverInterface interface {
	Create(ctx context.Context, apiserver *v1alpha1.Apiserver, opts v1.CreateOptions) (*v1alpha1.Apiserver, error)
	Update(ctx context.Context, apiserver *v1alpha1.Apiserver, opts v1.UpdateOptions) (*v1alpha1.Apiserver, error)
	UpdateStatus(ctx context.Context, apiserver *v1alpha1.Apiserver, opts v1.UpdateOptions) (*v1alpha1.Apiserver, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Apiserver, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ApiserverList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Apiserver, err error)
	ApiserverExpansion
}

// apiservers implements ApiserverInterface
type apiservers struct {
	client rest.Interface
	ns     string
}

// newApiservers returns a Apiservers
func newApiservers(c *RaihankhanV1alpha1Client, namespace string) *apiservers {
	return &apiservers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the apiserver, and returns the corresponding apiserver object, and an error if there is any.
func (c *apiservers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Apiserver, err error) {
	result = &v1alpha1.Apiserver{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("apiservers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Apiservers that match those selectors.
func (c *apiservers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ApiserverList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ApiserverList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("apiservers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested apiservers.
func (c *apiservers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("apiservers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a apiserver and creates it.  Returns the server's representation of the apiserver, and an error, if there is any.
func (c *apiservers) Create(ctx context.Context, apiserver *v1alpha1.Apiserver, opts v1.CreateOptions) (result *v1alpha1.Apiserver, err error) {
	result = &v1alpha1.Apiserver{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("apiservers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(apiserver).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a apiserver and updates it. Returns the server's representation of the apiserver, and an error, if there is any.
func (c *apiservers) Update(ctx context.Context, apiserver *v1alpha1.Apiserver, opts v1.UpdateOptions) (result *v1alpha1.Apiserver, err error) {
	result = &v1alpha1.Apiserver{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("apiservers").
		Name(apiserver.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(apiserver).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *apiservers) UpdateStatus(ctx context.Context, apiserver *v1alpha1.Apiserver, opts v1.UpdateOptions) (result *v1alpha1.Apiserver, err error) {
	result = &v1alpha1.Apiserver{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("apiservers").
		Name(apiserver.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(apiserver).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the apiserver and deletes it. Returns an error if one occurs.
func (c *apiservers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("apiservers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *apiservers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("apiservers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched apiserver.
func (c *apiservers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Apiserver, err error) {
	result = &v1alpha1.Apiserver{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("apiservers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
